// lib/mock-data.ts
// PuneJal — Realistic Pune Municipal Corporation mock dataset

import { Ward, MacroMetrics, BenchmarkEntry, WorkflowStep, DeepDiveData } from './types';

// Base reservoir volume (TMC) for runway calculation
export const BASE_RESERVOIR_TMC = 3.66;
export const BASE_DRAW_RATE = 1.55; // TMC/day

export const WARDS: Ward[] = [
  {
    id: 'W001',
    name: 'Karve Nagar',
    dmaCode: 'DMA-K04',
    headPressure: 0.42,
    pressureLabel: '⚠ Low',
    elevationDelta: 38,
    complaints24h: 142,
    status: 'critical',
    zone: 'West',
    population: 87400,
    pipelineLength: 12.4,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W002',
    name: 'Warje',
    dmaCode: 'DMA-W02',
    headPressure: 0.38,
    pressureLabel: '⚠ Low',
    elevationDelta: 45,
    complaints24h: 165,
    status: 'critical',
    zone: 'West',
    population: 102300,
    pipelineLength: 15.8,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W003',
    name: 'Dhayari',
    dmaCode: 'DMA-D07',
    headPressure: 0.35,
    pressureLabel: '⚠ Critical',
    elevationDelta: 52,
    complaints24h: 188,
    status: 'critical',
    zone: 'South-West',
    population: 68200,
    pipelineLength: 9.6,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W004',
    name: 'Ambegaon BK',
    dmaCode: 'DMA-A03',
    headPressure: 0.29,
    pressureLabel: '⚠ Critical',
    elevationDelta: 61,
    complaints24h: 213,
    status: 'critical',
    zone: 'South',
    population: 54800,
    pipelineLength: 8.2,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W005',
    name: 'Kondhwa',
    dmaCode: 'DMA-K11',
    headPressure: 0.44,
    pressureLabel: '⚠ Low',
    elevationDelta: 34,
    complaints24h: 127,
    status: 'critical',
    zone: 'South-East',
    population: 94600,
    pipelineLength: 14.1,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W006',
    name: 'Bibvewadi',
    dmaCode: 'DMA-B08',
    headPressure: 0.41,
    pressureLabel: '⚠ Low',
    elevationDelta: 41,
    complaints24h: 156,
    status: 'critical',
    zone: 'Central-South',
    population: 76300,
    pipelineLength: 11.3,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W007',
    name: 'Kothrud',
    dmaCode: 'DMA-K01',
    headPressure: 1.10,
    pressureLabel: 'Normal',
    elevationDelta: 12,
    complaints24h: 48,
    status: 'watch',
    zone: 'West',
    population: 148200,
    pipelineLength: 22.6,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W008',
    name: 'Bavdhan',
    dmaCode: 'DMA-B02',
    headPressure: 0.95,
    pressureLabel: 'Normal',
    elevationDelta: 18,
    complaints24h: 63,
    status: 'watch',
    zone: 'West',
    population: 62400,
    pipelineLength: 10.8,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W009',
    name: 'Pashan',
    dmaCode: 'DMA-P04',
    headPressure: 0.88,
    pressureLabel: 'Normal',
    elevationDelta: 22,
    complaints24h: 71,
    status: 'watch',
    zone: 'North-West',
    population: 83100,
    pipelineLength: 13.5,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W010',
    name: 'Katraj',
    dmaCode: 'DMA-K09',
    headPressure: 0.78,
    pressureLabel: 'Normal',
    elevationDelta: 28,
    complaints24h: 89,
    status: 'watch',
    zone: 'South',
    population: 91800,
    pipelineLength: 16.2,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W011',
    name: 'Dhanori',
    dmaCode: 'DMA-D03',
    headPressure: 0.82,
    pressureLabel: 'Normal',
    elevationDelta: 15,
    complaints24h: 74,
    status: 'watch',
    zone: 'North-East',
    population: 57200,
    pipelineLength: 9.4,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W012',
    name: 'Lohegaon',
    dmaCode: 'DMA-L02',
    headPressure: 0.92,
    pressureLabel: 'Normal',
    elevationDelta: 11,
    complaints24h: 55,
    status: 'watch',
    zone: 'North-East',
    population: 48600,
    pipelineLength: 8.7,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W013',
    name: 'Vishrantwadi',
    dmaCode: 'DMA-V05',
    headPressure: 0.74,
    pressureLabel: 'Normal',
    elevationDelta: 24,
    complaints24h: 96,
    status: 'watch',
    zone: 'North',
    population: 72900,
    pipelineLength: 12.1,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W014',
    name: 'Mundhwa',
    dmaCode: 'DMA-M06',
    headPressure: 0.71,
    pressureLabel: 'Normal',
    elevationDelta: 19,
    complaints24h: 108,
    status: 'watch',
    zone: 'East',
    population: 84300,
    pipelineLength: 13.8,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W015',
    name: 'Hadapsar',
    dmaCode: 'DMA-H05',
    headPressure: 1.65,
    pressureLabel: 'Optimal',
    elevationDelta: -5,
    complaints24h: 18,
    status: 'stable',
    zone: 'East',
    population: 136700,
    pipelineLength: 24.3,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W016',
    name: 'Shivajinagar',
    dmaCode: 'DMA-S01',
    headPressure: 1.80,
    pressureLabel: 'Optimal',
    elevationDelta: -8,
    complaints24h: 12,
    status: 'stable',
    zone: 'Central',
    population: 112400,
    pipelineLength: 18.9,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W017',
    name: 'Deccan Gymkhana',
    dmaCode: 'DMA-D01',
    headPressure: 1.72,
    pressureLabel: 'Optimal',
    elevationDelta: -3,
    complaints24h: 9,
    status: 'stable',
    zone: 'Central',
    population: 68900,
    pipelineLength: 11.6,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W018',
    name: 'Wanowrie',
    dmaCode: 'DMA-W07',
    headPressure: 1.55,
    pressureLabel: 'Optimal',
    elevationDelta: 2,
    complaints24h: 22,
    status: 'stable',
    zone: 'South-East',
    population: 98200,
    pipelineLength: 17.4,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W019',
    name: 'Yerwada',
    dmaCode: 'DMA-Y03',
    headPressure: 1.48,
    pressureLabel: 'Optimal',
    elevationDelta: 4,
    complaints24h: 31,
    status: 'stable',
    zone: 'North-East',
    population: 89400,
    pipelineLength: 15.2,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
  {
    id: 'W020',
    name: 'Aundh',
    dmaCode: 'DMA-A01',
    headPressure: 1.62,
    pressureLabel: 'Optimal',
    elevationDelta: -1,
    complaints24h: 14,
    status: 'stable',
    zone: 'North-West',
    population: 124800,
    pipelineLength: 21.5,
    lastUpdated: '2026-07-05T13:58:00Z',
  },
];

export const MACRO_METRICS: MacroMetrics = {
  reservoirCapacity: 14.2,
  reservoirTMC: 3.66,
  systemRunwayDays: 24,
  criticalWards: 6,
  computeRuntime: 0.018,
  gpuAcceleration: 2338,
};

export const BENCHMARK_DATA: BenchmarkEntry[] = [
  {
    name: 'CPU Baseline',
    runtime: 42.10,
    color: '#EF4444',
    label: '42.10s',
  },
  {
    name: 'GPU Accelerated',
    runtime: 0.018,
    color: '#10B981',
    label: '0.018s',
  },
];

export const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    id: 'bq',
    label: 'BigQuery',
    sublabel: 'SCADA Reads',
    icon: 'Database',
  },
  {
    id: 'cudf',
    label: 'cuDF',
    sublabel: 'Vector Joins',
    icon: 'Layers',
  },
  {
    id: 'cugraph',
    label: 'cuGraph',
    sublabel: 'Betweenness Centrality',
    icon: 'Network',
  },
];

export function generateDeepDiveData(ward: Ward): DeepDiveData {
  const pressureHistory = Array.from({ length: 12 }, (_, i) => ({
    time: `${String(8 + i).padStart(2, '0')}:00`,
    pressure: parseFloat((ward.headPressure + (Math.random() - 0.5) * 0.15).toFixed(2)),
  }));

  const complaintHistory = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day) => ({
    day,
    count: Math.round(ward.complaints24h * (0.7 + Math.random() * 0.6)),
  }));

  const recommendations =
    ward.status === 'critical'
      ? [
          'Activate emergency auxiliary pump at Zone sub-station',
          'Reduce draw from this DMA by 20% until pressure stabilises',
          'Deploy mobile water tankers to high-complaint streets',
          'Escalate to Hydraulics Lead for manual valve adjustment',
        ]
      : ward.status === 'watch'
      ? [
          'Schedule predictive maintenance for pressure gauges',
          'Monitor complaint trajectory over next 6h',
          'Pre-position standby pump unit in sector',
        ]
      : [
          'No immediate action required',
          'Continue telemetry monitoring at standard interval',
          'Confirm quarterly pipeline inspection is scheduled',
        ];

  return {
    ward,
    pressureHistory,
    complaintHistory,
    recommendations,
    networkNodes: Math.round(ward.population / 1200),
    flowRate: parseFloat((ward.pipelineLength * 12.4 + Math.random() * 20).toFixed(1)),
    reservoirFeed: ward.zone.includes('West') ? 'Khadakwasla Reservoir' : ward.zone.includes('East') ? 'Pawna Reservoir' : 'Temghar Reservoir',
  };
}

export function calculateRunway(drawRate: number, agriculturalDiversion: number): number {
  const effectiveVolume = BASE_RESERVOIR_TMC * (1 + agriculturalDiversion / 100 * 0.3);
  const adjustedDraw = drawRate;
  return parseFloat((effectiveVolume / adjustedDraw).toFixed(1));
}
